import { ASTNode } from './defines';
import type { GeneratorLiteral, FilterBlock, Block, ParsedPattern } from './defines';
import { Parser } from './parser';
import { evaluateFilter } from './evaluateFilter';
import {
  evaluateGenerator,
  sampleableGenerator,
  randomEvaluateGenerator,
  totalQueues
} from './evaluateGenerator';
import { product } from './utils';

const parser = new Parser();

function evaluateBlocks(blocks: Block[]): string[] {
  let runningQueues: string[][] = [];
  for (const block of blocks) {
    switch (block.type) {
      case ASTNode.GeneratorLiteral:
        runningQueues.push(evaluateGenerator(block));
        break;
      case ASTNode.FilterBlock: {
        const filterFunc = (queue: string) => evaluateFilter((block as FilterBlock).expr, queue);

        runningQueues = [
          (product(runningQueues) as Generator<string>).filter(filterFunc).toArray()
        ];
        break;
      }
    }
  }

  // cannot end with GeneratorLiteral so running iterators should only contain one element
  return runningQueues[0];
}

/**
 * Parses a given pattern into layered list for patterns to be appended together, patterns to be product together, individual blocks in AST
 */
export function parsePattern(pattern: string): ParsedPattern {
  if (pattern.length == 0) return [];

  // can list separate patterns together using semicolons to just append on
  const patterns = pattern.split(';');
  const parsed: (GeneratorLiteral | FilterBlock)[][][] = [];
  for (const pattern of patterns) {
    // separate into parts where filter will apply
    const parts = pattern.split(',');

    // parse everything and put in parsed
    const allBlocks: (GeneratorLiteral | FilterBlock)[][] = [];
    for (const part of parts) {
      let blocks = parser.parse(part);

      // starting with filter will just be removed as not filtering anything
      while (blocks[0].type == ASTNode.FilterBlock) blocks = blocks.slice(1);

      // GeneratorLiterals at the end can be own separate 'blocks'
      const allBlocksInitialEnd = allBlocks.length;
      while (blocks.length > 0 && blocks[blocks.length - 1].type == ASTNode.GeneratorLiteral)
        allBlocks.splice(allBlocksInitialEnd, 0, [blocks.pop()!]);

      if (blocks.length > 0) allBlocks.splice(allBlocksInitialEnd, 0, blocks);
    }

    parsed.push(allBlocks);
  }

  return parsed;
}

/**
 * Get all queues following sfinder pieces notation from parsedPattern output
 */
export function sfinderPieces(parsedPattern: ParsedPattern): string[] {
  const runningParts: string[] = [];

  for (const appendingParts of parsedPattern) {
    const runningQueues: string[][] = [];
    for (const blocks of appendingParts) {
      runningQueues.push(evaluateBlocks(blocks));
    }

    for (const queue of product(runningQueues) as Generator<string>) {
      runningParts.push(queue);
    }
  }

  return runningParts;
}

/**
 * Get a uniformally random queue from set generated by sfinder pieces notation
 */
export function randomSfinderPieces(
  parsedPattern: ParsedPattern,
  random: (a: number, b: number) => number
): string | null {
  if (parsedPattern.length == 0) return null;

  const weights: number[] = [];
  const choices: string[] = []; // choice for each part
  let total = 0;
  for (const appendingParts of parsedPattern) {
    let weight = 1;

    let queueChoice = '';

    for (const blocks of appendingParts) {
      if (blocks.length == 1) {
        // must be only a GeneratorLiteral and might be able to use faster function
        const block = blocks[0] as GeneratorLiteral;

        if (sampleableGenerator(block)) {
          queueChoice += randomEvaluateGenerator(block, random);
          weight *= totalQueues(block);
          continue;
        }
      }

      const evaluatedBlocks = evaluateBlocks(blocks);
      weight *= evaluatedBlocks.length;

      // no queues to choose from
      if (evaluatedBlocks.length == 0) return null;

      queueChoice += evaluatedBlocks[random(0, evaluatedBlocks.length)];
    }

    total += weight;
    weights.push(weight);
    choices.push(queueChoice);
  }

  if (choices.length == 1) return choices[0];

  const weightedChoice = random(0, total);
  let i = 0;
  let runningWeight = weights[i];
  while (runningWeight < weightedChoice) {
    i++;
    runningWeight += weights[i];
  }

  return choices[i];
}
