CREATE TYPE fraction AS (
  "numerator"   integer,
  "denominator" integer
);

CREATE DOMAIN setupid AS bytea 
  CHECK (octet_length(VALUE) = 5);

CREATE TABLE "setups" (
  "setup_id" setupid PRIMARY KEY,
  "leftover" varchar(7) NOT NULL,
  "build" varchar(100) NOT NULL,
  "cover_dependence" varchar(255) NOT NULL,
  "cover_data" bytea,
  "prev_setup" setupid,
  "next_setup" setupid,
  "fumen" varchar(1000) NOT NULL,
  "pieces" varchar(1000),
  "solve_percent" numeric(5,2),
  "solve_fraction" fraction,
  "mirror" setupid,
  "minimal_solves" varchar(1000),
  "path_file" varchar(500),
  "credit" varchar(255)

  CONSTRAINT valid_fraction CHECK (
    solve_fraction IS NULL OR (
      (solve_fraction).numerator IS NOT NULL AND
      (solve_fraction).denominator IS NOT NULL AND
      (solve_fraction).denominator <> 0
    )
  )
);

CREATE TABLE "saves" (
  "save_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setup_id" bytea NOT NULL,
  "save" varchar(255) NOT NULL,
  "description" varchar(255),
  "save_percent" numeric(5,2) NOT NULL,
  "save_fraction" fraction NOT NULL
);

COMMENT ON COLUMN "setups"."setup_id" IS '5 bytes';

COMMENT ON COLUMN "setups"."leftover" IS 'Pieces left from bag. Only TILJSZO allowed';

COMMENT ON COLUMN "setups"."build" IS 'Pieces used in setup. Only TILJSZO allowed';

COMMENT ON COLUMN "setups"."cover_dependence" IS 'Description of when setup is covered';

COMMENT ON COLUMN "setups"."cover_data" IS 'Bit string of what queues are covered from cover dependence. 1 if all covered';

COMMENT ON COLUMN "setups"."prev_setup" IS '5 bytes and references an id for oqb';

COMMENT ON COLUMN "setups"."next_setup" IS '5 bytes and references an id for oqb';

COMMENT ON COLUMN "setups"."pieces" IS 'Pieces used for solving. NULL if intended as step to full setup';

COMMENT ON COLUMN "setups"."solve_percent" IS 'Solve percent. NULL if intended as step to full setup';

COMMENT ON COLUMN "setups"."solve_fraction" IS 'Percise solve fraction';

COMMENT ON COLUMN "setups"."mirror" IS '5 bytes and references an id for mirror setup';

COMMENT ON COLUMN "setups"."credit" IS 'Credit for founder of setup';

COMMENT ON COLUMN "saves"."setup_id" IS '5 bytes';

COMMENT ON COLUMN "saves"."save" IS 'Pieces saved for next PC in extends pieces notation';

COMMENT ON COLUMN "saves"."description" IS 'Description of the save. Ex: One T or Two LJ';

COMMENT ON COLUMN "saves"."save_percent" IS 'Save percent';

COMMENT ON COLUMN "saves"."save_fraction" IS 'Percise save fraction';

ALTER TABLE "saves" ADD FOREIGN KEY ("setup_id") REFERENCES "setups" ("setup_id") ON DELETE CASCADE;
