name: Format Check

on: [push, pull_request]

jobs:
  build_and_test:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile 

      - name: Check Code Format
        run: npm run format_check

      - name: Download go misspell utility
        run: go install github.com/client9/misspell/cmd/misspell@latest

      - name: Run misspell to find misspelled words
        run: misspell -i initialy,strat -error ./src ./utils ./messages ./data ./docs README.md
