name: Format Check

on: [push, pull_request]

jobs:
  build_and_test:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: NPM install
        run: npm install

      - name: Check Code Format
        run: npm run format_check

      - name: Download go misspell utility
        run: go install github.com/client9/misspell/cmd/misspell@latest

      - name: Run misspell to find misspelled words
        run: misspell -i initialy,strat -error ./src ./utils ./messages ./data ./docs README.md
