name: Linting

on: [push, pull_request]

jobs:
  build_and_test:
    name: Linting and Typechecking
    runs-on: ubuntu-latest
    environment: actions

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Paraglide Files
        run: npx @inlang/paraglide-js compile --project ./project.inlang

      - name: Linting
        run: npm run lint
        env:
          PUBLIC_DEFAULT_KICKTABLE: ${{ vars.PUBLIC_DEFAULT_KICKTABLE }}
          PUBLIC_DEFAULT_HOLDTYPE: ${{ vars.PUBLIC_DEFAULT_HOLDTYPE }}
          PUBLIC_SUPABASE_URL: ${{ vars.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ vars.PUBLIC_SUPABASE_ANON_KEY }}
          PATH_UPLOAD_BUCKET: ${{ vars.PATH_UPLOAD_BUCKET }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Typechecking
        run: npm run check
        env:
          PUBLIC_DEFAULT_KICKTABLE: ${{ vars.PUBLIC_DEFAULT_KICKTABLE }}
          PUBLIC_DEFAULT_HOLDTYPE: ${{ vars.PUBLIC_DEFAULT_HOLDTYPE }}
          PUBLIC_SUPABASE_URL: ${{ vars.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ vars.PUBLIC_SUPABASE_ANON_KEY }}
          PATH_UPLOAD_BUCKET: ${{ vars.PATH_UPLOAD_BUCKET }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
