name: Run Populate Saves

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0,12 * * *' # run at midnight and 12

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: production 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile # Use pnpm install for pnpm projects. --frozen-lockfile is similar to npm ci


    - name: Set up JRE (Java Runtime Environment)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run populate saves
      run: pnpm tsx utils/populateSaves.ts
      env:
        PUBLIC_SUPABASE_URL: ${{ vars.PUBLIC_SUPABASE_URL }}
        PATH_UPLOAD_BUCKET: ${{ vars.PATH_UPLOAD_BUCKET }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
